### ISSUE TITLE
RSpec/EmtpyLineAfterSubject triggers on Rubocop comment

### ISSUE THREAD

**Issue by rpbaptist** [rubocop-hq/rubocop-rspec#734] opened 2019-01-28 15:06 UTC
```ruby
    # rubocop:disable Metrics/LineLength
    subject(:document_upload) do
      DocumentUpload.new(
        document,
        confirmation_url: "http://localhost:3000//document_upload_results?result=success",
        cancellation_url: "http://localhost:3000//document_upload_results?result=failure"
      )
    end
    # rubocop:enable Metrics/LineLength
```

I am disabling `Metrics/LineLength` because of https://github.com/rubocop-hq/rubocop/issues/5916

But then I get an alert on enabling a cop again.

Versions:

- rubocop (0.59.2)
- rubocop-rspec (1.25.1)

**Comment by bquorning** [comment] 2019-01-28 15:20
What is the error message, and which lines follow your code snippet?

**Comment by rpbaptist** [comment] 2019-01-28 16:54
```
RSpec/EmptyLineAfterSubject: Add empty line after subject.
    subject(:document_upload) do ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dgollahon** [comment] 2019-01-28 18:54
Related issue: #603. I _think_ I fixed this in #642.

@rpbaptist Can you please try this on the latest version of `rubocop-rspec` and let me know if you still have this problem?

**Comment by pirj** [comment] 2019-05-10 01:09
Technically,
```
    # rubocop:enable Metrics/LineLength
```
is not an empty line.

```
    # rubocop:disable Metrics/LineLength
    subject(:long) { "ergoqiawhgpajdkjslfjszldfjlasjdflkasjdflkjaslkdfjaslkdfjalksdjflkasjdflaskjdf" }
    # rubocop:enable Metrics/LineLength
    before { ... }
```
is still too dense.

I can still reproduce this issue by adding the following example to `spec/rubocop/cop/rspec/empty_line_after_subject_spec.rb`:
```
  it 'handles subject followed by a comment' do
    expect_no_offenses(<<-RUBY)
      RSpec.describe User do
        subject { described_user }
        # not an empty line
        let(:foo) {}
      end
    RUBY
  end
```

**Comment by dgollahon** [comment] 2019-06-18 08:41
@pirj I don't actually think that was the original problem, but @rpbaptist can correct me if I'm wrong. I believe he was using a slightly out of date version of `rubocop-rspec` which wouldn't allow you to do  (adapting your example) this:

```ruby
it 'handles subject followed by a comment' do
    expect_no_offenses(<<-RUBY)
      RSpec.describe User do
        subject { described_user }
        # not an empty line
        
        let(:foo) {}
      end
    RUBY
  end
```

and would require you to write:

```ruby
it 'handles subject followed by a comment' do
    expect_no_offenses(<<-RUBY)
      RSpec.describe User do
        subject { described_user }

        # not an empty line

        let(:foo) {}
      end
    RUBY
  end
```

or

```ruby
it 'handles subject followed by a comment' do
    expect_no_offenses(<<-RUBY)
      RSpec.describe User do
        subject { described_user }

        # not an empty line
        let(:foo) {}
      end
    RUBY
  end
```

Which was pretty awkward for `rubocop:enable` statements. I fixed and unified all the blank line logic so it accepted any blank line between the rspec constructs, with or without comments in between.

Flagging

```ruby
  it 'handles subject followed by a comment' do
    expect_no_offenses(<<-RUBY)
      RSpec.describe User do
        subject { described_user }
        # not an empty line
        let(:foo) {}
      end
    RUBY
  end
```

has always been intended behavior.

I'm closing this since I think the issue was an out of date `rubocop-rspec`, but if I'm wrong, feel free to re-open, @rpbaptist.

**Closed by dgollahon** 2019-06-18 08:41 UTC
