### ISSUE TITLE
Variable `let` assignment causes crash in `OverwritingSetup` cop

### ISSUE THREAD

**Issue by abrom** [rubocop-hq/rubocop-rspec#639] opened 2018-06-13 00:41 UTC
Hi there,

The latest release of `rubocop-rspec` has highlighted an issue in a codebase I manage, but did so by causing a parser crash in the `OverwritingSetup` cop.

The use-case is having a variable as the argument in a `let` assignment. For example:

```
%i[foo bar baz].each do |prop|
  let(prop) { nil }
end
```
as a shorthand for
```
let(:foo) { nil }
let(:bar) { nil }
let(:baz) { nil }
```

The problem is that the `OverwritingSetup` cop assumes that the parameter passed to the `let` call will always be a symbol.

I've written a fix (to ignore) and a test case for the above issue, but it begs the question as to whether the above pattern is really that great an idea. I'm not a fan TBH and have changed the problem code on my side, but what are your thoughts on adding a new cop to identify this sort of thing? Ignoring it likely isn't a great idea given you could have something silly like:
```
%i[foo bar].each_with_index do |prop, index|
  let(prop) { index }
end
```
The `OverwritingSetup` cop really wouldn't know what to do about it.

It feels like it might be putting too much on the `OverwritingSetup` to have the offences handled there but it wouldn't be inconceivable to do so??

Happy to submit a PR to either:
a) ignore the problem
b) identify the problem in `OverwritingSetup`
c) ignore it in `OverwritingSetup` and identify it in a new cop

**Comment by dgollahon** [comment] 2018-06-13 04:50
Hi @abrom, I believe this is a duplicate of #624, so I'll close it. Correct me if I'm wrong or have missed any additional detail.

#625 is in progress and should resolve the issue in the next release.

**Closed by dgollahon** 2018-06-13 04:50 UTC

**Comment by abrom** [comment] 2018-06-13 04:53
Thanks @dgollahon, yes you're right. Questions RE the solution still stand though. Like I said, i've got a solution that works (by 'ignoring' non symbol first attribute). But there should be questions about what we do in that case given it would clearly allow the cop to essentially be skipped

**Comment by dgollahon** [comment] 2018-06-13 05:07
> Like I said, i've got a solution that works (by 'ignoring' non symbol first attribute). But there should be questions about what we do in that case given it would clearly allow the cop to essentially be skipped

If you're talking about trying to catch cases where dynamic definitions overlap:

That's not something `rubocop-rspec` can reliably detect because the value might not be known until runtime.

As a note, if you are worried about this, I believe `ruby` (or perhaps it was `rspec`?) will emit a warning for duplicates, but you have to have something that asserts your suite doesn't emit warnings. `rspec` has an option to turn warnings into errors if you're interested.

I also run a separate project called [rspectre](https://github.com/dgollahon/rspectre) that monkey-patches `rspec` and observes tests as they run. It's not a perfectly polished library and requires running your whole test suite to get results, but it can detect when `let`s and other spec constructs are unused at runtime. In the case of a duplicate definition, one of them is necessarily unused and would be caught.

If you're talking about discouraging dynamically named lets in general:

Creating a new cop that requires all lets to only be defined with symbols would probably be reasonable or maybe creating a new cop that looks for enumeration in certain parts of the spec dsls could work as well (though I think this is useful on rare occasions).

**Comment by Darhazer** [comment] 2018-06-14 08:13
@abrom I also think this is an anti-pattern but it's a matter for another cop. I'd accept such a cop that checks for dynamic let declarations.
