### ISSUE TITLE
Errors when inspecting Rspecs

### ISSUE THREAD

**Issue by Midnighter** [rubocop-hq/rubocop-rspec#236] opened 2016-11-06 15:25 UTC
I have a rails engine and ran the following command:

```
rubocop -d -R --require rubocop-rspec
```
I get multiple occurrences of the following errors:

```
An error occurred while RSpec/ExampleLength cop was inspecting
comparison of Fixnum with nil failed
```
and
```
An error occurred while RSpec/NotToNot cop was inspecting
undefined method `to_sym' for nil:NilClass
```

Info snippet
```
0.45.0 (using Parser 2.3.1.4, running on ruby 2.3.1 x86_64-linux)
```

I should mention that I get no such error when omitting `--require rubocop-rspec`.

Please let me know if you need further information.

**Comment by Midnighter** [comment] 2016-11-06 16:21
Came across another one:

```
An error occurred while Style/WordArray cop was inspecting '...'.
comparison of Fixnum with String failed
```

**Comment by backus** [comment] 2016-11-06 20:51
Thanks for the reports! I'll look into these. Can you share the offending code that caused these errors? Hard for me to debug otherwise

**Comment by backus** [comment] 2016-11-07 20:21
Ping @Midnighter. Any examples would be very helpful. I was unable to reproduce yesterday in the dark

**Comment by Midnighter** [comment] 2016-11-07 21:07
My bad, I'll try to provide something minimal later tonight.

**Comment by backus** [comment] 2016-11-07 21:08
Thanks!

**Comment by Midnighter** [comment] 2016-11-12 18:15
Apologies for the long wait. I have put my spec file [in this gist](https://gist.github.com/Midnighter/bc44b9d3cc1c26616f504d45a5e0ada1).

I've created a new project using rvm and Ruby 2.3.1. Then installed rubocop and rubocop-rspec.

Running either `rubocop language_spec.rb` or `rubocop -R language_spec.rb` shows style problems but no errors.

Running `rubocop --require rubocop-rspec language_spec.rb` or `rubocop -R --require rubocop-rspec language_spec.rb` shows 27 errors. I hope this helps you.

Contents of the `Gemfile.lock`:

```
GEM
  remote: https://rubygems.org/
  specs:
    ast (2.3.0)
    parser (2.3.1.4)
      ast (~> 2.2)
    powerpack (0.1.1)
    rainbow (2.1.0)
    rubocop (0.45.0)
      parser (>= 2.3.1.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    rubocop-rspec (1.8.0)
      rubocop (>= 0.42.0)
    ruby-progressbar (1.8.1)
    unicode-display_width (1.1.1)

PLATFORMS
  ruby

DEPENDENCIES
  rubocop
  rubocop-rspec

BUNDLED WITH
   1.13.6
```

**Comment by bquorning** [comment] 2016-11-12 20:20
I cannot reproduce the issue that you are seeing. Do you have a `.rubocop.yml` configuration file, and would it be possible for you to share it?

**Comment by Midnighter** [comment] 2016-11-12 20:28
I didn't use a configuration file when running this in an isolated new project.

**Comment by bquorning** [comment] 2016-11-12 20:37
Yeah, I’ve been able to reproduce the issue. I’ll have a look at it.

**Comment by bquorning** [comment] 2016-11-12 20:54
It looks like rubocop-rspec's default configuration doesn't get picked up unless there is a RuboCop configuration file in your project. While it’s not perfect, you can work around the problem with a `touch .rubocop.yml` for now.

**Comment by Midnighter** [comment] 2016-11-12 21:02
OK, that does solve it for me in the isolated case. In the original project I already have a `.rubocop.yml` but get errors anyhow. Here are the contents:

`.rubocop`:
```
--display-cop-names
```

`.rubocop.yml`:
```
inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
Rails:
  Enabled: true
```

and I just tried: if I do **not** inherit then I get no errors but when I do (generated with `rubocop --auto-gen-config`) the errors appear.

**Comment by bquorning** [comment] 2016-11-12 21:18
@backus I’m not well versed in the config loader parts of RuboCop. Ok if I hand this one over to you?

**Comment by backus** [comment] 2016-11-13 01:01
Minimal reproduction

```
$ cat rubocop_rspec_236_spec.rb
it 'example' do
end
$ bundle exec rubocop --require rubocop-rspec --debug --only RSpec/ExampleLength rubocop_rspec_236_spec.rb
For /Users/johnbackus/Projects/gists/rubocop-rspec-issue-236: configuration from /Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/config/default.yml
Inheriting configuration from /Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/config/enabled.yml
Inheriting configuration from /Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/config/disabled.yml
Inspecting 1 file
Scanning /Users/johnbackus/Projects/gists/rubocop-rspec-issue-236/rubocop_rspec_236_spec.rb
An error occurred while RSpec/ExampleLength cop was inspecting /Users/johnbackus/Projects/gists/rubocop-rspec-issue-236/rubocop_rspec_236_spec.rb.
comparison of Fixnum with nil failed
/Users/johnbackus/Projects/rubocop-rspec/lib/rubocop/cop/rspec/example_length.rb:40:in `>'
/Users/johnbackus/Projects/rubocop-rspec/lib/rubocop/cop/rspec/example_length.rb:40:in `on_block'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cop/commissioner.rb:41:in `block (2 levels) in on_block'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cop/commissioner.rb:96:in `with_cop_error_handling'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cop/commissioner.rb:40:in `block in on_block'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cop/commissioner.rb:39:in `each'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cop/commissioner.rb:39:in `on_block'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/ast_node/traversal.rb:12:in `walk'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cop/commissioner.rb:58:in `investigate'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cop/team.rb:120:in `investigate'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cop/team.rb:108:in `offenses'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cop/team.rb:51:in `inspect_file'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:243:in `inspect_file'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:190:in `block in do_inspection_loop'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:222:in `block in iterate_until_no_changes'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:215:in `loop'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:215:in `iterate_until_no_changes'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:186:in `do_inspection_loop'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:101:in `block in file_offenses'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:111:in `file_offense_cache'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:99:in `file_offenses'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:90:in `process_file'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:65:in `each'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:65:in `reduce'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:65:in `each_inspected_file'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/runner.rb:36:in `run'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cli.rb:72:in `execute_runner'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/lib/rubocop/cli.rb:27:in `run'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/bin/rubocop:13:in `block in <top (required)>'
/Users/johnbackus/.rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/Users/johnbackus/.gem/ruby/2.3.1/gems/rubocop-0.45.0/bin/rubocop:12:in `<top (required)>'
/Users/johnbackus/.gem/ruby/2.3.1/bin/rubocop:23:in `load'
/Users/johnbackus/.gem/ruby/2.3.1/bin/rubocop:23:in `<top (required)>'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/cli/exec.rb:74:in `load'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/cli/exec.rb:27:in `run'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/cli.rb:332:in `exec'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/cli.rb:20:in `dispatch'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/cli.rb:11:in `start'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/exe/bundle:34:in `block in <top (required)>'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/johnbackus/.gem/ruby/2.3.1/gems/bundler-1.13.2/exe/bundle:26:in `<top (required)>'
/Users/johnbackus/.gem/ruby/2.3.1/bin/bundle:23:in `load'
/Users/johnbackus/.gem/ruby/2.3.1/bin/bundle:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while RSpec/ExampleLength cop was inspecting /Users/johnbackus/Projects/gists/rubocop-rspec-issue-236/rubocop_rspec_236_spec.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.45.0 (using Parser 2.3.1.4, running on ruby 2.3.1 x86_64-darwin16)
Finished in 0.10977799999818671 seconds
```

**Comment by backus** [comment] 2016-11-13 01:31
Making some progress. FWIW, I didn't actually implement this configuration injection stuff and I have a plan to eventually do away with this (bbatsov/rubocop#3414).

> It looks like rubocop-rspec's default configuration doesn't get picked up unless there is a RuboCop configuration file in your project. 

In all rubocop runs `ConfigLoader.default_configuration` is called (memoizing the class instance variable) before `RuboCop::RSpec.inject!` is invoked. The reason adding a config file works is because [`merge_with_defaults`](https://github.com/bbatsov/rubocop/blob/d4cfe7dfa06551ea2ccb9da64025272b9338dfaa/lib/rubocop/config_loader.rb#L117) is invoked when there is a config file which picks up the injected defaults. This bug has probably been around since the beginning of rubocop-rspec so I'm going to see if I can find a workaround but if it takes longer than an hour or so to figure out I think I might just aim to resolve this issue by upstreaming better third party support.

Thanks for the report @Midnighter and thanks for helping with this issue @bquorning :)

**Comment by backus** [comment] 2016-11-13 02:26
Actually my explanation isn't entirely correct. Basically, if a configuration file isn't present for a given directory, RuboCop falls back to its default configuration and short circuits the procedure of mixing in defaults (where our defaults get mixed in). See this line https://github.com/bbatsov/rubocop/blob/d4cfe7dfa06551ea2ccb9da64025272b9338dfaa/lib/rubocop/config_loader.rb#L97

Unfortunately I think this is impossible for us to resolve properly and I'd rather not dig us into a deeper hole by monkey patching rubocop's implementation details.

I'm going to leave this issue open because it is still a bug for our end user but unfortunately I can't promise a quick fix and the workaround @bquorning suggested is the best I can recommend for now.

**Comment by Midnighter** [comment] 2016-11-13 16:39
Do you want me to file an issue with rubocop itself then? Also, from your explanation of the bug I don't understand why inheriting from a different configuration also causes this problem.

**Comment by backus** [comment] 2016-11-14 06:11
I'm not sure why it breaks in that case if your `.rubocop.yml` file is actually being picked up. I am pretty confident though that the issue is just our monkey patching not being applied properly in certain cases. You don't need to file an upstream issue.

**Comment by binkley** [comment] 2017-02-18 16:43
I have the same issue.  At the bottom of the failure:
```
Mention the following information in the issue report:
0.47.1 (using Parser 2.4.0.0, running on ruby 2.2.5 x86_64-cygwin)
RuboCop failed!
```
Versions:
```
$ gem list | grep ruboc
rubocop (0.47.1)
rubocop-rspec (1.11.0)
```
My setup is to add `rubocop-rspec` to gemspec, and in `Rakefile`:
```
require 'rubocop/rake_task'

RuboCop::RakeTask.new do |rubocop|
  rubocop.requires << %w(rubocop-rspec)
end
```
Please note @bquorning 's workaround _did work for me_.  I'm hoping this comment may give you another data point.  Thanks!

**Comment by bquorning** [comment] 2018-04-13 13:48
@mateusluizfb Using `bundle exec` will use the versions of RuboCop and RuboCop RSpec that are locked in Gemfile.lock. Without `bundle exec` you will (probably) use the most recent versions installed on your system.

Probably the underlying issue has been (accidentally?) fixed in one of the gems.

**Comment by bquorning** [comment] 2018-04-13 13:52
> Probably the underlying issue has been (accidentally?) fixed in one of the gems.

Negative. I can still reproduce the issue on the most recent versions.

**Comment by pirj** [comment] 2020-11-06 19:44
@bquorning Can you still reproduce?

Passes just fine on my end:
```
$ bundle exec rubocop --require rubocop-rspec --debug --only RSpec/ExampleLength rubocop_rspec_236_spec.rb
For /Users/pirj/source/rubocop-rspec: configuration from /Users/pirj/source/rubocop-rspec/.rubocop.yml
configuration from /Users/pirj/.rvm/gems/ruby-2.6.3@rubocop-rspec/gems/rubocop-performance-1.8.1/config/default.yml
configuration from /Users/pirj/.rvm/gems/ruby-2.6.3@rubocop-rspec/gems/rubocop-performance-1.8.1/config/default.yml
Inheriting configuration from /Users/pirj/source/rubocop-rspec/.rubocop_todo.yml
Inspecting 1 file
Scanning /Users/pirj/source/rubocop-rspec/rubocop_rspec_236_spec.rb
.

1 file inspected, no offenses detected
Finished in 1.014236000002711 seconds
```

**Comment by bquorning** [comment] 2020-11-06 21:46
I can also no longer reproduce the problem.

**Closed by bquorning** 2020-11-06 21:46 UTC
Labels: bug
