### ISSUE TITLE
Still getting "RSpec/FilePath has the wrong namespace - should be Rails"

### ISSUE THREAD

**Issue by dominicsayers** [rubocop-hq/rubocop-rspec#405] opened 2017-04-28 11:21 UTC
If I run `rubocop` from the command line with the option ` --only RSpec/FilePath` I get the following:

```bash
$ rubocop --only RSpec/FilePath
--only option: RSpec/FilePath has the wrong namespace - should be Rails
Inspecting 21 files
.....................

$ rubocop -v
0.48.1

$ cat Gemfile.lock | grep rubocop-rspec
    rubocop-rspec (1.15.0)
  rubocop-rspec
```
My `.rubocop.yml` is as follows:

```YAML
---
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Exclude:
    - 'tmp/**/*'

Style/MixinGrouping:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Exclude:
    - '**/*_spec.rb'

StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

DotPosition:
  EnforcedStyle: leading
  Enabled: true

ClassAndModuleChildren:
  EnforcedStyle: nested
  Enabled: true

Documentation:
  Enabled: false

FileName:
  Enabled: true

LineLength:
  Max: 120
  Enabled: true

Style/ExtraSpacing:
  Enabled: true

Lint/LiteralInInterpolation:
  AutoCorrect: true

Style/ModuleFunction:
  EnforcedStyle: extend_self # Allows us to have private methods too

Style/PercentLiteralDelimiters:
  # Hound and CodeClimate are currently using an old version of Rubocop with
  # different defaults, so we set them explicitly here.
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
```

**Comment by Darhazer** [comment] 2017-04-28 14:30
This does not happen when rubocop-rspec is required manually.
`rubocop --require rubocop-rspec --only RSpec/FilePath`
Perhaps it's a bug in `rubocop` itself

**Comment by backus** [comment] 2017-04-28 19:57
Do you have a `.rubocop_todo.yml` file @dominicsayers? If so you might need to add `require: rubocop-rspec` to that as well

**Comment by aried3r** [comment] 2018-04-16 13:04
I can confirm @Darhazer's workaround works. As to the recommendation of adding `require: rubocop-rspec` to `.rubocop_todo.yml`: Since that's an auto-generated file, I think that would be quite tedious.

Is this bug caused because of a name conflict with another cop?

**Comment by pirj** [comment] 2019-10-27 18:27
Wondering if it's still the case, since in the earliest RuboCop supported, 0.68.1, this cop is now [named `Naming/FileName`](https://github.com/rubocop-hq/rubocop/blob/98b03406bcfa091e26a6bd936f3107ce9d9e372d/config/default.yml#L1864).

**Comment by bquorning** [comment] 2020-11-06 22:40
I assume this has been fixed on RuboCop 1.x and RuboCop RSpec 2.x. If you still run into this issue @dominicsayers, please re-open the issue.

**Closed by bquorning** 2020-11-06 22:40 UTC
