### ISSUE TITLE
RSpec/NamedSubject should be ignored in shared examples/contexts

### ISSUE THREAD

**Issue by ixti** [rubocop-hq/rubocop-rspec#706] opened 2018-10-12 22:44 UTC
I think NamedSubject should ignore shard examples

**Comment by Darhazer** [comment] 2018-10-12 22:50
Duplicate of #453

**Closed** 2018-10-12 22:50 UTC

**Comment by ixti** [comment] 2018-10-12 22:58
@Darhazer oh, indeed. Sorry. Forgot to search first.
