### ISSUE TITLE
Not enable RSpec/LetSetup by default 

### ISSUE THREAD

**Issue by goodniceweb** [rubocop-hq/rubocop-rspec#887] opened 2020-03-26 18:03 UTC
My first issue here I want to start with words of thankfulness: this project helped me write better rspec tests. Big thanks to all members and contributors!

Talking about the issue: `RSpec/LetSetup`. Across multiple projects I face the same issue: _we keep removing this rule_. That's why I open this issue, just because I think I'm not the only person in the world who does it. 

[Considering](https://github.com/rubocop-hq/rubocop-rspec/issues/94#issuecomment-243310009) [all](https://github.com/rubocop-hq/rubocop-rspec/issues/94#issuecomment-437113188) [those](https://github.com/rubocop-hq/rubocop-rspec/issues/94) [examples](https://github.com/rubocop-hq/rubocop-rspec/issues/94) and [official documentation](http://www.betterspecs.org/#let) I'd ask to make this code disabled by default.

**Comment by bquorning** [comment] 2020-03-26 19:50
This seems like a duplicate of #94, and I still stand by [my response](https://github.com/rubocop-hq/rubocop-rspec/issues/94#issuecomment-441591296) there, which quotes one of the RSpec maintainers:

> I find `before` and `let` to be useful for particular situations, but find that they often get mis-used/abused in the wild, unfortunately. My rule of thumb is to use them when there's a compelling benefit, but don't reach for them as the default way to write specs.

betterspecs.org is _not_ the official documentation. The [official documentation](https://relishapp.com/rspec/rspec-core/v/3-9/docs/helper-methods/let-and-let) has no recommendation for or against using `let!`.

**Comment by pirj** [comment] 2020-03-26 20:52
> words of thankfulness: this project helped me write better rspec tests. Big thanks to all members and contributors!

Thank you!

Can you find proof across [`real-world-ruby-apps`](https://github.com/jeromedalbert/real-world-ruby-apps) and [`real-world-rails`](https://github.com/eliotsykes/real-world-rails) that for projects that use RSpec it's disabled significantly more often than not?

`rubocop-rspec` is configurable, and we encourage people to tune the configuration to fit the style established in their projects. We should probably emphasize that just like our parent project, `rubocop` does:
> is extremely flexible and most aspects of its behavior can be tweaked via various configuration options.

The defaults of `rubocop-rspec` tend to be normalized with the [community-driven RSpec style guide](https://github.com/rubocop-hq/rspec-style-guide), while usually `rubocop-rspec` provides a superset of what the style guide recommends.

[RuboCop's version and cop enablement policy](https://docs.rubocop.org/en/stable/versioning/#pending-cops) states that the cops will be enabled on major versions, and the exception to this would only be cops that are really rarely used and not used by many. Other cops, even possibly mutually exclusive, will be enabled, with some default enforced styles.
On minor version changes, when new cops will be introduced, or enforced styles will be changed, you will have to explicitly enable or disable such cops.
Yes, that probably means your `.rubocop.yml` will grow big, but that also means that it's **you** who's in control, not those who maintain RuboCop or its extensions.

The defaults are carefully picked in such a way that they make sure the code is consistent, gotcha-free, and canonical.

I'm not getting into the discussion if `let!` is canonical or not, I must admit I have a bias here, so let's see what the numbers say. Your call @goodniceweb.

**Comment by pirj** [comment] 2020-04-03 17:27
Please feel free to reopen if there's some evidence that `RSpec/LetSetup` is in general disabled more often than not.

**Closed by pirj** 2020-04-03 17:27 UTC

**Comment by ioquatix** [comment] 2021-01-05 05:15
I also agree with the OP.
