### ISSUE TITLE
Various cops crash when .rubocop.yml is missing

### ISSUE THREAD

**Issue by mensfeld** [rubocop-hq/rubocop-rspec#637] opened 2018-06-12 14:26 UTC
Steps to reproduce:

```
git clone https://github.com/mensfeld/broken-rubocop-rspec3
cd broken-rubocop-rspec3
./run.sh
```

Output:

```
Using ast 2.4.0
Using bundler 1.16.2
Using jaro_winkler 1.5.1
Using parallel 1.12.1
Using parser 2.5.1.0
Using powerpack 0.1.2
Using rainbow 3.0.0
Using ruby-progressbar 1.9.0
Using unicode-display_width 1.4.0
Using rubocop 0.57.2
Using rubocop-rspec 1.26.0
Bundle complete! 2 Gemfile dependencies, 11 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Inspecting 2 files
.An error occurred while RSpec/DescribedClass cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/OverwritingSetup cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ItBehavesLike cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ItBehavesLike cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ItBehavesLike cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/NotToNot cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/NotToNot cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/NotToNot cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/ExampleLength cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
To see the complete backtrace run rubocop -d.
C

Offenses:

spec/example_spec.rb:1:1: C: RSpec/FilePath: Spec path should end with anything*_spec.rb.
describe Anything do
^^^^^^^^^^^^^^^^^

2 files inspected, 1 offense detected

21 errors occurred:
An error occurred while RSpec/DescribedClass cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
An error occurred while RSpec/ExpectChange cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
An error occurred while RSpec/OverwritingSetup cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
An error occurred while RSpec/ItBehavesLike cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
An error occurred while RSpec/ItBehavesLike cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
An error occurred while RSpec/ItBehavesLike cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
An error occurred while RSpec/NotToNot cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:1:0.
An error occurred while RSpec/NotToNot cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:2:2.
An error occurred while RSpec/NotToNot cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
An error occurred while RSpec/ExampleLength cop was inspecting /home/mencio/Pulpit/broken-rubocop-rspec3/spec/example_spec.rb:4:2.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues
```

It crashes when executed following way:

```
bundle exec rubocop --only RSpec --require rubocop-rspec
```

**Comment by Darhazer** [comment] 2018-06-12 14:41
Seems the same issue as in #613

**Comment by mensfeld** [comment] 2018-06-12 14:44
@Darhazer not really. I mean I don't have a rubocop config and all of it relies on the default once.

**Comment by mensfeld** [comment] 2018-06-12 14:48
@Darhazer as an update. With following config still fails (although less drastically):

```ruby
require: rubocop-rspec

AllCops:
  Include:
    - spec/**/*_spec.rb
```

**Comment by bquorning** [comment] 2018-06-12 18:06
Ah, I think that is the forgotten issue from https://github.com/rubocop-hq/rubocop-rspec/issues/613#issuecomment-389777840

> The “nothing works when there is no .rubocop.yml file” seems to have been present for a long, long time. Let’s leave that one for now.

Thanks for opening a new issue.

**Comment by mensfeld** [comment] 2018-06-12 18:10
@bquorning as I said - when I have a small rubocop.yml with the config as followed:

```
require: rubocop-rspec

AllCops:
  Include:
    - spec/**/*_spec.rb
```

it also fails. Just less drastically (but still). Probably due to a space between let and the name:

```ruby
let (:a) { 1 }
```

**Comment by bquorning** [comment] 2018-06-12 18:34
Again with reporting two bugs at the same time 😄

I’ll take a look at then both.

**Comment by bquorning** [comment] 2018-06-12 19:21
That issue is actually a duplicate of #624, which has a proposed fix in #625.

**Comment by mensfeld** [comment] 2018-06-13 06:52
> Again with reporting two bugs at the same time
Sorry ;) I run rubocop-rspec couple thousand of times for multiple projects automatically, so you can always ping me with a prerelease and we can give it a spin ;)

**Comment by dgollahon** [comment] 2018-06-15 09:14
@mensfeld Looks like all the other issues have been fixed as of `1.27.0` (thanks for the great reproduction script!) but the missing `.rubocop.yml` issue persists, so I've updated the title.

**Comment by mensfeld** [comment] 2018-06-15 10:12
@dgollahon any time. As I said, I run this stuff a lot for many codebases (hundreds) so always after upgrades I see many errors ;)

**Comment by dgollahon** [comment] 2018-06-15 18:16
>  I run this stuff a lot for many codebases (hundreds)

Just curious, what causes you to run it for hundreds of codebases? Do you have that many projects that you oversee? Or is there some other supporting reason?

**Comment by mensfeld** [comment] 2018-06-16 09:45
@dgollahon I run self-hosted service for analyzing ruby repos: https://coditsu.io/
You can check it out here: https://app.coditsu.io/karafka/commit_builds and for example results from rubocop rspec: https://app.coditsu.io/karafka/builds/validations/6ea37309-98f8-4d46-ae31-0b537db06b6a/offenses

This allows me to bump single instance of rubocop-rspec (as well as other tools) and rerun many analysis for all the projects, so there is no need to have anything apart from business and specs within repositories. Makes management much easier. I've built it after years of building simple scripts and tools for exactly that job.

**Comment by dgollahon** [comment] 2018-06-16 21:28
@mensfeld neat 👍

**Comment by bquorning** [comment] 2020-11-15 20:03
I tried to reproduce this issue in various versions of RuboCop today, and it looks like it was fixed by https://github.com/rubocop-hq/rubocop/pull/7632 in RuboCop v0.82.0.

Please re-open if you are still running into this issue.

**Closed by bquorning** 2020-11-15 20:03 UTC
Labels: bug
