### ISSUE TITLE
NoMethodError on NilClass exception when running RSpec/DescribedClass

### ISSUE THREAD

**Issue by glindsey** [rubocop-hq/rubocop-rspec#801] opened 2019-08-08 13:36 UTC
Hey folks:

Ran into this when recently running Rubocop on our codebase; it doesn't appear to be the same as the other closed issues above, although of course I could be wrong there.

I've censored the filename as I have no idea what our company's guidelines are on that sort of info, but I don't think it's pertinent to the trace. The particular portion of the file it errors on is simply a `describe ClassName` line.

Thanks!

```
$ bundle exec rubocop FILENAME.rb --only RSpec/DescribedClass -d
For /var/www/current: configuration from /var/www/current/.rubocop.yml
configuration from /home/vagrant/.gem/ruby/2.3.6/gems/rubocop-performance-1.4.1/config/default.yml
configuration from /home/vagrant/.gem/ruby/2.3.6/gems/rubocop-performance-1.4.1/config/default.yml
Default configuration from /home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/config/default.yml
configuration from /home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rails-2.0.1/config/default.yml
configuration from /home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rails-2.0.1/config/default.yml
configuration from /home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/config/default.yml
configuration from /home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/config/default.yml
Inheriting configuration from /var/www/current/rubocop_rules.yml
Inheriting configuration from /var/www/current/.rubocop_todo.yml
Inheriting configuration from /var/www/current/.rubocop_layout_todo.yml
Inheriting configuration from /var/www/current/.rubocop_lint_todo.yml
Inheriting configuration from /var/www/current/.rubocop_metrics_todo.yml
Inheriting configuration from /var/www/current/.rubocop_naming_todo.yml
Inheriting configuration from /var/www/current/.rubocop_performance_todo.yml
Inheriting configuration from /var/www/current/.rubocop_rails_todo.yml
Inheriting configuration from /var/www/current/.rubocop_rspec_todo.yml
Inheriting configuration from /var/www/current/.rubocop_security_todo.yml
Inheriting configuration from /var/www/current/.rubocop_style_todo.yml
.rubocop.yml: Metrics/AbcSize:Max overrides the same parameter in .rubocop_style_todo.yml
.rubocop.yml: Style/SpecialGlobalVars:EnforcedStyle overrides the same parameter in .rubocop_style_todo.yml
Inspecting 1 file
Scanning FILENAME.rb
An error occurred while RSpec/DescribedClass cop was inspecting FILENAME:4:2.
undefined method `first' for nil:NilClass
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:147:in `collapse_namespace'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:132:in `full_const_name'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:128:in `offensive_described_class?'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:114:in `offensive?'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:80:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:61:in `on_block'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:128:in `with_cop_error_handling'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:55:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:32:in `block (2 levels) in <class:Commissioner>'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:150:in `on_while'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:50:in `block in on_begin'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:50:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:50:in `on_begin'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:13:in `walk'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:44:in `investigate'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/team.rb:119:in `investigate'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/team.rb:107:in `offenses'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:277:in `inspect_file'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:225:in `block in do_inspection_loop'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:257:in `block in iterate_until_no_changes'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:250:in `loop'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:250:in `iterate_until_no_changes'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:221:in `do_inspection_loop'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:124:in `block in file_offenses'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:142:in `file_offense_cache'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:122:in `file_offenses'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:110:in `process_file'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:86:in `each'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:86:in `reduce'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:86:in `each_inspected_file'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:73:in `inspect_files'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/runner.rb:39:in `run'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cli.rb:210:in `execute_runner'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cli.rb:80:in `execute_runners'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/lib/rubocop/cli.rb:51:in `run'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/exe/rubocop:13:in `block in <top (required)>'
/home/vagrant/.rubies/ruby-2.3.6/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/vagrant/.gem/ruby/2.3.6/gems/rubocop-0.74.0/exe/rubocop:12:in `<top (required)>'
/home/vagrant/.gem/ruby/2.3.6/bin/rubocop:23:in `load'
/home/vagrant/.gem/ruby/2.3.6/bin/rubocop:23:in `<top (required)>'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/home/vagrant/.gem/ruby/2.3.6/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/home/vagrant/.gem/ruby/2.3.6/bin/bundle:23:in `load'
/home/vagrant/.gem/ruby/2.3.6/bin/bundle:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while RSpec/DescribedClass cop was inspecting FILENAME.rb:4:2.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.74.0 (using Parser 2.6.3.0, running on ruby 2.3.6 x86_64-linux)
Finished in 0.7201318870065734 seconds
```
The `rubocop-rspec` version being used is 1.35.

**Comment by pirj** [comment] 2019-08-08 15:26
@glindsey Can you please post the contents of FILENAME.rb, or at least some context around that part?

If you're not in a position to provide live code, feel free to obfuscate it and narrow down the issue to that piece of code that makes the cop break.

**Comment by nickcampbell18** [comment] 2019-08-13 11:01
Hi @pirj, we've seen a similar issue and I've got a reproduction case for you:

```ruby
require "spec_helper"

module Foo
  RSpec.describe Bar do
    it do
      puts described_class::CONSTANT
    end
  end
end
```

The problem seems to arise when the whole spec is inside a module block. We do this for our application to make it easier to resolve related code in the same module without needed to explicitly use the full module name everywhere. The error happens because `#const_name(node)` is returning `nil` - there is no branch of the condition that accomodates this `node`:

```
#<RuboCop::Cop::RSpec::DescribedClass>)> node
=> s(:const,
  s(:send, nil, :described_class), :CONSTANT
```

**Comment by pirj** [comment] 2019-08-13 11:16
@nickcampbell18 This is [fixed](https://github.com/rubocop-hq/rubocop-rspec/pull/800/files#diff-25a2fc59ee58bcb3fbabb644ac504ccbR276) in #800. Thanks for the detailed reproduction example.

I hope the issue @glindsey is experiencing is the same as described in #799, but would really like to confirm that.

**Comment by glindsey** [comment] 2019-08-13 12:58
Phil:

I’m sorry, I’ve been on vacation and will be for the rest of this week. When I get back I’ll check the code to see if it is similar to Nick’s case — and thanks so much for your quick response!

— Greg

**Comment by pirj** [comment] 2019-08-20 09:36
Hey @glindsey, have you had a chance to check against `rubocop-rspec`'s `master`, does it fix the issue you are experiencing?

**Comment by pirj** [comment] 2019-08-22 15:14
@glindsey A polite ping.

**Comment by shanecav84** [comment] 2019-08-22 17:54
I had the same error, and the fix in `master` is working.

**Comment by pirj** [comment] 2019-08-22 19:04
Thanks, good to know @shanecav84 !

@bquorning The stack traces are near identical, I believe it's the same issue fixed in #800. Do you think it's possible to close this, or should we release and wait for the confirmation first?

**Comment by glindsey** [comment] 2019-08-22 20:54
Phil:

Sorry! I checked the fix, and it does indeed resolve the problem. Thanks!

- Greg

**Comment by bquorning** [comment] 2019-08-22 20:58
Thank you @glindsey, that’s good to hear. 👍  I’ll close the issue, then.

**Closed by bquorning** 2019-08-22 20:58 UTC
