### ISSUE TITLE
RSpec/EmptyExampleGroup and CustomIncludeMethods with contexts

### ISSUE THREAD

**Issue by incubus** [rubocop-hq/rubocop-rspec#1050] opened 2020-10-21 12:58 UTC
Hi! 
   
 RSpec/EmptyExampleGroup doesn't use CustomIncludeMethods with contexts. Here is an example with 1.44.1 version:

```ruby
# frozen_string_literal: true

describe 'Object' do
  context 'with test' do
    example_request 'Remove' do
      expect(status).to eq 204
    end

    context 'with error' do
      example_request 'Update error' do
        expect(status).to eq 422
      end
    end
  end
end
```

```yml
RSpec/EmptyExampleGroup:
  CustomIncludeMethods:
    - example_request
```

```
spec/acceptance/test_spec.rb:9:5: C: RSpec/EmptyExampleGroup: Empty example group detected.
    context 'with error' do
    ^^^^^^^^^^^^^^^^^^^^
```

 There is not problem with 1.43.2 version. Thanks!

**Comment by pirj** [comment] 2020-10-21 13:40
Thanks for reporting!

`CustomIncludeMethods` were intended to facilitate the detection of aliases to `it_behaves_like`, not example group aliases.
It turns out it [lacks support for such aliases being called with a block](https://github.com/rubocop-hq/rubocop-rspec/blob/26c6d4a1574a3fbf4ec7a1f729e87ed9d5ab9303/lib/rubocop/cop/rspec/empty_example_group.rb#L103), like in your case.

There's a pull request fixing this https://github.com/rubocop-hq/rubocop-rspec/pull/1015, but we decided not to merge it. Feel free to point your Gemfile to that fork/branch if you like as a short-term solution.

However, with #956 soon to be merged, we don't plan and wouldn't recommend to invest effort into fixing this.
Along with it, we plan to drop the `CustomIncludeMethods` config option altogether, see https://github.com/rubocop-hq/rubocop-rspec/pull/1007.

If you don't have custom cops based on `rubocop-rspec`'s code and would like this to be fixed ASAP along with 2.0 release, the best you can do is to check some recent pull request's `edge-rubocop` CI failure and send a pull request fixing at least some of them.

I'll keep this ticket open just in case.

**Comment by pirj** [comment] 2020-11-06 17:51
#956 has been released in [2.0](https://github.com/rubocop-hq/rubocop-rspec/releases/tag/v2.0.0), so this should be fixed given that you [configure your RSpec DSL aliases](https://docs.rubocop.org/rubocop-rspec/2.0/usage.html#rspec-dsl-configuration) for RuboCop RSpec.

Please feel free to reopen if it won't affect how `RSpec/EmptyExampleGroup` behaves.

**Closed by pirj** 2020-11-06 17:51 UTC

**Comment by pirj** [comment] 2020-11-06 17:58
Forgot to mention that `CustomIncludeMethods` have been removed in #1007

**Comment by pirj** [comment] 2020-11-06 17:59
Also, this is a duplicate of https://github.com/rubocop-hq/rubocop-rspec/issues/1006
