### ISSUE TITLE
Error in RSpec/LeadingSubject while inspecting

### ISSUE THREAD

**Issue by elad-maimon** [rubocop-hq/rubocop-rspec#803] opened 2019-08-11 02:41 UTC
Got an error:
"An error occurred while RSpec/LeadingSubject cop was inspecting...."

This is the subject line it fails:

    subject { ProtoModel.new(field1: 'f1', field2: nested_model).serialize_to_proto }

These is relevant code:

    class ProtoModel
      include ProtoSerializable
    end
   
    let(:nested_model) { NestedProtoModel.new }

    class NestedProtoModel
      include ProtoSerializable
    end

## RuboCop version
0.68.1 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin18)

**Comment by pirj** [comment] 2019-08-11 08:36
@elad-maimon Can you please provide a bit more context? 

What are the rubocop/rubocop-rspec versions being used?
What is the backtrace?
What is the example and its ancestor example groups?

I can't reproduce it locally:

```ruby
# spec/a_spec.rb
RSpec.describe 'A' do
  class NestedProtoModel
    include ProtoSerializable
  end

  subject { ProtoModel.new(field1: 'f1', field2: nested_model).serialize_to_proto }

  let(:nested_model) { NestedProtoModel.new }
end
```

```sh
$ rubocop --only RSpec/LeadingSubject spec/a_spec.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

**Comment by pirj** [comment] 2019-08-18 21:00
@elad-maimon Ping.

**Comment by pirj** [comment] 2019-08-22 15:12
@elad-maimon Ping.

**Comment by pirj** [comment] 2019-09-15 12:38
@elad-maimon A friendly reminder to provide more context regarding the issue.

**Comment by pirj** [comment] 2019-11-25 19:59
@elad-maimon I've tested your code against a pretty old `rubocop-rspec` version 1.26.0 and can reproduce the issue:
```
undefined method `method_name' for #<RuboCop::AST::ClassNode:0x00007fdfe3ce2988>                                                                                                    
Did you mean?  method                                                                                                                                                               
/Users/pirj/source/rubocop-rspec/lib/rubocop/cop/rspec/leading_subject.rb:59:in `let?'                                                                                              
/Users/pirj/source/rubocop-rspec/lib/rubocop/cop/rspec/leading_subject.rb:42:in `block in on_block'                 
/Users/pirj/.rvm/gems/ruby-2.5.5@rubocop-rspec/gems/rubocop-0.76.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/Users/pirj/.rvm/gems/ruby-2.5.5@rubocop-rspec/gems/rubocop-0.76.0/lib/rubocop/ast/node.rb:190:in `each'            
/Users/pirj/.rvm/gems/ruby-2.5.5@rubocop-rspec/gems/rubocop-0.76.0/lib/rubocop/ast/node.rb:190:in `each_child_node'                                                                 
/Users/pirj/source/rubocop-rspec/lib/rubocop/cop/rspec/leading_subject.rb:39:in `on_block' 
```

This was in some way fixed in more recent versions. I suggest you update `rubocop-rspec`.
If you feel that there's anything actionable in the scope of this ticket, please feel free to reopen.

@bquorning I believe we can close this.

**Closed** 2019-11-25 21:25 UTC
